package com.mohak1712.register;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Register.proto

public interface DeRegisterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeRegister)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>optional string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>optional string port = 2;</code>
   */
  java.lang.String getPort();
  /**
   * <code>optional string port = 2;</code>
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
