package com.mohak1712.register;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Register.proto

public final class RegisterOuterClass {
  private RegisterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Register_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Register_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeRegister_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeRegister_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Register.proto\"$\n\010Register\022\n\n\002ip\030\001 \001(\t" +
      "\022\014\n\004port\030\002 \001(\t\"&\n\nDeRegister\022\n\n\002ip\030\001 \001(\t" +
      "\022\014\n\004port\030\002 \001(\t\"*\n\010Response\022\017\n\007success\030\001 " +
      "\001(\010\022\r\n\005error\030\002 \001(\t2X\n\020DiscoveryService\022 " +
      "\n\010register\022\t.Register\032\t.Response\022\"\n\ndere" +
      "gister\022\t.Register\032\t.ResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Register_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Register_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Register_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_DeRegister_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeRegister_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Success", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
